redis:
  image: jiramot/redis
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
  stdin_open: true
  tty: true

redis-lb:
  ports:
  - 6379:7000/tcp
  tty: true
  image: rancher/load-balancer-service
  links:
  - redis:redis
  stdin_open: true
  labels:
    io.rancher.scheduler.global: 'true'
