.catalog:
  name: "mongo-cluster"
  version: "3.3 cluster with expose port"
  description: "MongoDB Replica Set"
  uuid: mongodb-1
  minimum_rancher_version: v0.46.0
  questions:
    - variable: replset_name
      description: "Name of the MongoDB replicaSet"
      label: "ReplicaSet Name"
      type: "string"
      required: true
      default: "rs0"
mongo-cluster:
  scale: 3
  retain_ip: true
  metadata:
    mongo:
      yml:
        replset.name: "${replset_name}"
