router:
  ports:
  - 27017:27017/tcp
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: mongo=yes
  tty: true
  entrypoint:
  - /entrypoint.sh
  command:
  - mongos
  - --configdb
  - rs-conf/mongo_config_1:27017,mongo_config_2:27017,mongo_config_3:27017
  image: mongo:3.3
  stdin_open: true
setup:
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.start_once: 'true'
    io.rancher.scheduler.affinity:host_label: mongo=yes
  tty: true
  entrypoint:
  - /setup.sh
  image: registry.fungjai.com/mongo-setup
  stdin_open: true
config:
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: mongo=yes
  tty: true
  command:
  - /usr/bin/mongod
  - --configsvr
  - --replSet
  - rs-conf
  - --port
  - '27017'
  - --dbpath
  - /data/db
  image: mongo:3.3
  stdin_open: true
rs3:
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: mongo=yes
  tty: true
  command:
  - /usr/bin/mongod
  - --replSet
  - rs3
  image: mongo:3.3
  stdin_open: true
rs2:
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: mongo=yes
  tty: true
  command:
  - /usr/bin/mongod
  - --replSet
  - rs2
  image: mongo:3.3
  stdin_open: true
rs1:
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: mongo=yes
  tty: true
  command:
  - /usr/bin/mongod
  - --replSet
  - rs1
  image: mongo:3.3
  stdin_open: true
