.catalog:
  name: "Galera DB"
  version: fungjai-v0
  description: |
    Galera Cluster based on MariaDB 10.0.22
galera:
  scale: 3
  metadata:
    mysqld: |
      max_allowed_packet = 32M
      sql_mode = "STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
      innodb_file_per_table = 1
      innodb_autoinc_lock_mode=2
      query_cache_size=0
      query_cache_type=0
      innodb_flush_log_at_trx_commit=0
      binlog_format=ROW
      default-storage-engine=innodb
      wsrep_provider=/usr/lib/galera/libgalera_smm.so
      wsrep_provider_options="gcache.size = 2G"
      wsrep_sst_method=mysqldump
      wsrep_sst_auth=root:
      progress=1
galera-lb:
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
